create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  reservation_code text not null unique,
  customer_name text not null,
  phone text not null,
  address text not null,
  delivery_date date not null,
  delivery_time time not null,
  payment_method text not null check (payment_method in ('Yape','Plin')),
  quantity integer not null check (quantity between 1 and 10),
  unit_price numeric(10,2) not null default 69.90,
  status text not null default 'pending' check (status in ('pending','paid','cancelled')),
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- No INSERT/UPDATE público. Toda escritura pasa por endpoints server-side.
-- SUPABASE_SERVICE_ROLE_KEY jamás se expone al navegador.

create or replace view public.public_campaign_stats as
select coalesce(sum(quantity) filter (where status = 'paid'), 0)::bigint as paid_orders
from public.orders;

grant select on public.public_campaign_stats to anon;
